### PR TITLE
add event click, mousever, and mouseleave API

### PR DESCRIPTION
**Pull request by superpikar**
- change background on event hover
- add event click, mousever, and mouseleave
- add an example in example/milestones-event_api.html
- update README
- change CRLF to LF on *.js file and *.less file

### CODE REVIEW

**Comment by superpikar** [comment]
Hi @walterra,

You've made a great chart! It helps me visualize meetings history in my project.

How do you think about my pull request proposal? The reason behind my pull request is I need to trigger an event when user mouse over, mouse leave, or click the text in the milestones chart.

**Comment by walterra** [comment]
Hey @superpikar — thank you so much for the PR, happy to hear you like the visualization! I'm traveling at the moment but will have a closer look next week!

**Comment by walterra** [comment]
@superpikar I just updated some dependencies in `master` which now already includes `package-lock.json` and `yarn.lock`, can you please rebase your PR so that the conflicts are resolved.

**Comment by superpikar** [comment]
@walterra Git rebase is done. 
Btw, this is my first time doing git rebase, let me know if I am doing something wrong.

**Comment by walterra** [comment]
@superpikar I'm not completely sure what went wrong with your rebase but somehow it still shows a lot of changes in the diff which are already part of `master`. I cherry-picked your original contribution into a new branch and created another PR here https://github.com/walterra/d3-milestones/pull/4

I will close this PR and merge the other one. Because of the cherry-pick your code will still be attributed to you in the git history even if the new PR was created by me. Thank you very much for the contribution, it will be part of the next release/tag.

**Comment by superpikar** [comment]
@walterra  Um, maybe I should learn more about git. Thank you for merging my contribution :)

**Pull request closed without merging**
